#Deployment
###controllers/pb-deploy.tml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
    spec:
      containers:
        - name: employee-container
          image: sriram1406/employee-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '1'
              memory: '1G'
            requests:
              cpu: '1'
              memory: '1G'
          ports:
            - containerPort: 8085
      
